[functions]
external_node_modules = [
"bcrypt",
"body-parser",
"cors",
"dotenv",
"express",
"jsonwebtoken",
"nodemon",
"pg",
"pg-hstore",
"react-native-geolocation-service",
"sequelize",
"serverless-http",
]
node_bundler = "esbuild"
[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/api/:splat"
