[functions]
external_node_modules = [
"bcrypt",
"body-parser",
"cors",
"dotenv",
"express",
"jsonwebtoken",
"nodemon",
"pg",
"pg-hstore",
"react-native-geolocation-service",
"sequelize",
"serverless-http",
]
node_bundler = "esbuild"
[[redirects]]
force = true
from = "/*"
status = 200
to = "/.netlify/functions/app/:splat"

[build]
  command = "npm run build"             # Command to build your app (if applicable)
  functions = "netlify/functions"       # Directory for Netlify Functions
  publish = "public"  
